dir = File.expand_path(File.join(File.dirname(__FILE__), 'json_support'))
require File.join(dir, 'core')
require File.join(dir, 'model')
require File.join(dir, 'model', 'properties')
require File.join(dir, 'model', 'relationships')
require File.join(dir, 'property')
require File.join(dir, 'resource')